onlyBuiltDependencies:
  - ' '
  - '-'
  - /
  - '@'
  - '@prisma/client'
  - a
  - b
  - c
  - d
  - e
  - g
  - h
  - i
  - l
  - m
  - n
  - o
  - p
  - prisma
  - r
  - s
  - t
  - u
  - v
  - w
  - x
